// Joaquin Lavori — portfolio data
// Edit this file to add, remove or reorder projects. Everything on the
// site is generated from what's in here — no need to touch the HTML.

const SITE = {
  name: "Joaquin Lavori",
  tagline: "Branding & Illustration",
  email: "joaquinmotor@gmail.com",
  instagram: "instagram.com/joaquin.motor",
  instagramUrl: "https://instagram.com/joaquin.motor",
  location: "Byron Bay, NSW, Australia",
  aboutShort:
    "Joaquin Lavori is a graphic designer and illustrator from Buenos Aires, now based in Byron Bay, Australia. His practice moves between art direction, branding and hand-drawn illustration for surf, skate and streetwear brands, bars and independent businesses.",
  featuredIn: [
    "7 Capas Magazine",
    "La Nación",
    "Revista Otra",
    "Mustique Magazine",
    "Porsche Magazine",
  ],
  awards: [
    {
      title: "Realization Award",
      detail:
        "“Eternity” group exhibition curated by Maurizio Cattelan — Art Basel Cities, Buenos Aires. 2018.",
    },
  ],
  aboutLong: [
    "Joaquin Maria Lavori (b. 1987, Buenos Aires) is a graphic designer and illustrator now living and working in Byron Bay, NSW. He trained as a graphic designer at the University of Buenos Aires, and spent several years alongside painters, art critics and curators before moving fully into design and illustration.",
    "His work sits between two disciplines: art direction and brand identity on one side, and hand-drawn illustration on the other. He has led visual identity and campaign work for brands including Vans Argentina, and built capsule collections and illustration systems for surf, skate and streetwear labels across Argentina, the US and Australia. In parallel, he maintains an independent illustration and tattoo practice, having worked as a guest artist in studios across the Americas, Europe and Asia.",
    "His work has been exhibited individually and in groups in Buenos Aires, New York and Barcelona, including “Eternity”, a group show curated by Maurizio Cattelan for Art Basel Cities in 2018, for which he received a Realization Award.",
  ],
  education: [
    { year: "2013", detail: "Bachelor of Graphic Design, University of Buenos Aires" },
    { year: "2024–now", detail: "Entrepreneur & New Business, Greystone College, Melbourne" },
    { year: "2016–18", detail: "Art critic and painting, Diana Aisenberg, private studio, Buenos Aires" },
    { year: "2018", detail: "Author Curatorship Seminar, University Torcuato Di Tella, Buenos Aires" },
  ],
  roles: [
    { year: "2015–17 / 2022–24", detail: "Vans Argentina — Art Director & Art Ambassador" },
    { year: "2014–15", detail: "Combo Latam — Illustrator & Graphic Designer" },
    { year: "2012–14", detail: "Tiempo de otros tiempos, Mustique Magazine, Porsche Magazine — Graphic Designer" },
  ],
  exhibitions: [
    { year: "2024", detail: "Dermis, solo show — Bardo Factory, Byron Bay" },
    { year: "2018", detail: "Eternity, curated by Maurizio Cattelan — Art Basel Cities, Buenos Aires" },
    { year: "2017", detail: "Memories of them, solo show — Fleur Noire, New York" },
    { year: "2014 / 2012", detail: "Time is Gold / Time is Money, solo shows — Buenos Aires" },
  ],
  residencies:
    "Guest tattoo artist in 19 studios across 13 countries between 2018–19, including New York, Los Angeles, Toronto, Seoul, Taipei, Tokyo, Berlin, Barcelona, Madrid, London, Bristol, Paris, Milan and Bangkok.",
};

const PROJECTS = [
  {
    slug: "vans",
    brand: "Vans Argentina",
    category: "Art Direction & Illustration",
    location: "Buenos Aires, Argentina",
    year: "2015–17 & 2022–24",
    blurb: "Art direction, retail and campaign illustration for Vans Argentina.",
    body: [
      "Art Director for Vans Argentina, developing visual content for retail spaces, events, campaigns and printed materials. Responsibilities included art direction, layout design, visual adaptations for points of sale, event graphics and catalog design.",
      "In parallel, acted as an Art Ambassador for the brand, representing its creative values through illustration, visual storytelling and collaboration with athletes and artists.",
      "The role required a deep understanding of the brand's identity, close coordination with marketing teams, and consistency across all visual touchpoints.",
    ],
    link: "https://vans.com.ar",
    linkLabel: "vans.com.ar",
    hero: "assets/img/vans/hero.jpg",
    gallery: [
      "assets/img/vans/hero.jpg",
      "assets/img/vans/02.jpg",
      "assets/img/vans/03.jpg",
      "assets/img/vans/04.jpg",
      "assets/img/vans/05.jpg",
      "assets/img/vans/06.jpg",
    ],
  },
  {
    slug: "lacalle",
    brand: "La Calle Bar",
    category: "Illustration & Graphic Design",
    location: "Buenos Aires, Argentina",
    year: "2025",
    blurb: "Hand-drawn illustration system for a Buenos Aires bar, from menu to merch.",
    body: [
      "Worked closely with the client to develop and execute visual concepts across multiple brand projects. Responsibilities included concept development, illustration, art direction, layout design and preparation of final production files.",
      "Managed the creative process from initial brief to final delivery, ensuring visual consistency and alignment with the bar's identity. All illustrations were created by hand and later digitised for print and production.",
      "Design decisions, visual storytelling and technical requirements were coordinated closely with the owners throughout, to deliver tailored graphic solutions across plates, apparel, signage and printed menus.",
    ],
    link: "https://instagram.com/lacallebar",
    linkLabel: "instagram.com/lacallebar",
    hero: "assets/img/lacalle/hero.jpg",
    gallery: [
      "assets/img/lacalle/02.jpg",
      "assets/img/lacalle/hero.jpg",
      "assets/img/lacalle/03.jpg",
      "assets/img/lacalle/04.jpg",
      "assets/img/lacalle/05.jpg",
      "assets/img/lacalle/06.jpg",
      "assets/img/lacalle/07.jpg",
      "assets/img/lacalle/08.jpg",
    ],
  },
  {
    slug: "lightningbolt",
    brand: "Lightning Bolt",
    category: "Apparel Capsule & Illustration",
    location: "Buenos Aires, Argentina",
    year: "2022",
    blurb: "A collaborative apparel capsule rooted in surf culture and hand-drawn linework.",
    body: [
      "Developed a collaborative apparel capsule for Lightning Bolt, creating original hand-drawn illustrations inspired by the brand's heritage and surf culture roots.",
      "The work included concept development, illustration and preparation of print-ready artworks for screen printing across garments and accessories. All graphics were created by hand and later digitised for production.",
      "The process focused on respecting the brand's legacy while translating it into a contemporary visual language, through close collaboration and feedback.",
    ],
    link: "https://lightningbolt.com.ar",
    linkLabel: "lightningbolt.com.ar",
    hero: "assets/img/lightningbolt/hero.jpg",
    gallery: [
      "assets/img/lightningbolt/hero.jpg",
      "assets/img/lightningbolt/02.jpg",
      "assets/img/lightningbolt/03.jpg",
      "assets/img/lightningbolt/04.jpg",
      "assets/img/lightningbolt/05.jpg",
      "assets/img/lightningbolt/06.jpg",
    ],
  },
  {
    slug: "laguitarrita",
    brand: "La Guitarrita",
    category: "Branding & Menu Design",
    location: "Buenos Aires, Argentina",
    year: "2023",
    blurb: "A 60th-anniversary visual refresh for a traditional Buenos Aires pizzeria.",
    body: [
      "A full visual update across multiple brand touchpoints, including logo and menu redesign, packaging, printed materials and digital assets, for La Guitarrita's 60th anniversary.",
      "The process was based on understanding the client's history, values and current needs, translating them into a refreshed visual system. The logo was redesigned to maintain its original essence while updating it to meet new functional and communication requirements.",
      "Through meetings and feedback, the brand identity was refined to feel contemporary, recognisable and aligned with the business's evolution.",
    ],
    link: "https://laguitarrita.com.ar",
    linkLabel: "laguitarrita.com.ar",
    hero: "assets/img/laguitarrita/hero.jpg",
    gallery: ["assets/img/laguitarrita/hero.jpg", "assets/img/laguitarrita/02.jpg"],
  },
  {
    slug: "fatima",
    brand: "Fatima Surfboards",
    category: "Capsule Collection & Branding",
    location: "Byron Bay, Australia",
    year: "2025",
    blurb: "A capsule collection and alternate logo mark for a custom-shape surfboard brand.",
    body: [
      "Development of a capsule apparel collection, original illustrations and custom artwork across multiple brand applications. All graphics were created by hand and later digitised for production.",
      "The work also included embroidery artwork, print-ready designs and a hand-painted special edition surfboard. A new logo was designed as an alternative to the main brand mark, maintaining the brand's core identity while offering a flexible option for different uses.",
      "The process was collaborative, based on feedback and refinement to ensure consistency and authenticity.",
    ],
    link: "https://fatimasurfboards.com",
    linkLabel: "fatimasurfboards.com",
    hero: "assets/img/fatima/hero.jpg",
    gallery: [
      "assets/img/fatima/hero.jpg",
      "assets/img/fatima/02.jpg",
      "assets/img/fatima/03.jpg",
      "assets/img/fatima/04.jpg",
      "assets/img/fatima/05.jpg",
    ],
  },
  {
    slug: "fortyspotted",
    brand: "Forty Spotted",
    category: "Illustration & Merchandising",
    location: "Tasmania, Australia",
    year: "2024",
    blurb: "Playful character illustration for a Tasmanian gin's summer merch campaign.",
    body: [
      "Original digital illustrations based on a client brief, translating key brand elements into clear and playful visual assets for a summer merchandising campaign.",
      "The work included creating vector-based artworks representing the product and signature details of the brand. Final files were prepared for screen printing as well as digital platforms.",
      "Close collaboration with the marketing team ensured visual consistency and alignment with the brand's youthful identity.",
    ],
    link: "https://fortyspotted.com",
    linkLabel: "fortyspotted.com",
    hero: "assets/img/fortyspotted/hero.jpg",
    gallery: [
      "assets/img/fortyspotted/hero.jpg",
      "assets/img/fortyspotted/02.jpg",
      "assets/img/fortyspotted/03.jpg",
      "assets/img/fortyspotted/04.jpg",
      "assets/img/fortyspotted/05.jpg",
      "assets/img/fortyspotted/06.jpg",
    ],
  },
  {
    slug: "logos",
    brand: "Logos",
    category: "Selected Logotypes",
    location: "2020–2025",
    year: "",
    blurb: "A selection of logo marks developed for clients over the last five years.",
    body: [
      "A selection of logos developed over recent years. Each project is based on listening to the client, understanding their needs, and working through feedback and meetings to define the essence of the brand.",
      "The goal is to simplify that essence into a clear, functional and timeless logo that represents the brand in the most honest way.",
    ],
    type: "logos",
    marks: [
      { name: "The Movement", style: "hand", url: "https://themovement.land" },
      { name: "AIM", style: "sacred", url: "https://aimmiami.org" },
      { name: "Ceremonia", style: "bold", url: "https://weareceremonia.com" },
      { name: "Soldadores", style: "condensed", url: "https://soldadores.com" },
      { name: "Fatima", style: "pill", url: "https://fatimasurfboards.com" },
      { name: "Motor", style: "spaced", url: "https://motormfg.com" },
      { name: "TFM", style: "stencil", url: "https://thefrothmedia.com" },
      { name: "La Guitarrita", style: "script", url: "https://laguitarrita.com.ar" },
    ],
  },
];
